services:
  comet:
    image: g0ldyy/comet:latest
    container_name: comet
    restart: unless-stopped
    volumes:
      - comet_data:/app/data
    environment:
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - PUBLIC_BASE_URL=https://comet.timelesshub.my.id
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=data/comet.db
      - SCRAPE_TORRENTIO=live
      - TORRENTIO_URL=https://torrentio.strem.fun
      - SCRAPE_ZILEAN=live
      - ZILEAN_URL=https://zileanfortheweebs.midnightignite.me
      - SCRAPE_STREMTHRU=live
      - STREMTHRU_SCRAPE_URL=https://stremthru.13377001.xyz
      - SCRAPE_MEDIAFUSION=live
      - MEDIAFUSION_URL=https://mediafusion.elfhosted.com
      - MEDIAFUSION_LIVE_SEARCH=False
      - SCRAPE_BITMAGNET=live
      - BITMAGNET_URL=https://bitmagnetfortheweebs.midnightignite.me
      - SCRAPE_TORRENTSDB=live
      - SCRAPE_TORBOX=False
      - SCRAPE_PEERFLIX=False
    networks:
      - caddy_proxy

  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    environment:
      - SECRET_KEY=${AIOSTREAMS_SECRET_KEY}
      - BASE_URL=https://aio.timelesshub.my.id
      - DATABASE_URI=sqlite://./data/db.sqlite
      - AIOSTREAMS_AUTH=${AIOSTREAMS_AUTH}
    volumes:
      - aiostreams_data:/app/data
    networks:
      - caddy_proxy

volumes:
  aiostreams_data:
  comet_data:

networks:
  caddy_proxy:
    external: true
